-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS tpre612_data_warehouse.dim_date
(
    date_id serial NOT NULL,
    start_date date,
    end_date date,
    monday boolean,
    tuesday boolean,
    wednesday boolean,
    thursday boolean,
    friday boolean,
    saturday boolean,
    sunday boolean,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_id),
    CONSTRAINT uq_dim_date UNIQUE (start_date, end_date, monday, tuesday, wednesday, thursday, friday, saturday, sunday)
);

CREATE TABLE IF NOT EXISTS tpre612_data_warehouse.dim_energie
(
    energy_id serial NOT NULL,
    geo text COLLATE pg_catalog."default",
    vehicle text COLLATE pg_catalog."default",
    energy_type text COLLATE pg_catalog."default",
    year integer,
    energy_value double precision,
    CONSTRAINT dim_energie_pkey PRIMARY KEY (energy_id),
    CONSTRAINT uq_dim_energie UNIQUE (geo, vehicle, energy_type, year)
);

CREATE TABLE IF NOT EXISTS tpre612_data_warehouse.dim_gare
(
    gare_id serial NOT NULL,
    name text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    is_main_station boolean,
    CONSTRAINT dim_gare_pkey PRIMARY KEY (gare_id),
    CONSTRAINT uq_dim_gare_name_country UNIQUE (name, country)
);

CREATE TABLE IF NOT EXISTS tpre612_data_warehouse.dim_operateur
(
    agency_id text COLLATE pg_catalog."default" NOT NULL,
    agency_name text COLLATE pg_catalog."default",
    agency_url text COLLATE pg_catalog."default",
    agency_timezone text COLLATE pg_catalog."default",
    agency_lang text COLLATE pg_catalog."default",
    CONSTRAINT dim_operateur_pkey PRIMARY KEY (agency_id)
);

CREATE TABLE IF NOT EXISTS tpre612_data_warehouse.dim_route
(
    route_id integer NOT NULL,
    agency_id text COLLATE pg_catalog."default",
    route_long_name text COLLATE pg_catalog."default",
    origin text COLLATE pg_catalog."default",
    destination text COLLATE pg_catalog."default",
    countries text COLLATE pg_catalog."default",
    CONSTRAINT dim_route_pkey PRIMARY KEY (route_id)
);

CREATE TABLE IF NOT EXISTS tpre612_data_warehouse.dim_train
(
    trip_id text COLLATE pg_catalog."default" NOT NULL,
    route_id integer,
    trip_headsign text COLLATE pg_catalog."default",
    trip_origin text COLLATE pg_catalog."default",
    destination_arrival_time time without time zone,
    duration interval,
    distance double precision,
    is_night_train boolean,
    CONSTRAINT dim_train_pkey PRIMARY KEY (trip_id)
);

CREATE TABLE IF NOT EXISTS tpre612_data_warehouse.fact_trajet_train
(
    fact_id serial NOT NULL,
    train_id text COLLATE pg_catalog."default",
    route_id integer,
    operator_id text COLLATE pg_catalog."default",
    gare_depart_id integer,
    gare_arrivee_id integer,
    date_ids integer[],
    distance_km double precision,
    duree_minutes double precision,
    emissions_co2 double precision,
    passengers double precision,
    average_speed double precision,
    is_night_train boolean,
    CONSTRAINT fact_trajet_train_pkey PRIMARY KEY (fact_id)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.agencies
(
    agency_id text COLLATE pg_catalog."default" NOT NULL,
    agency_name text COLLATE pg_catalog."default" NOT NULL,
    agency_url text COLLATE pg_catalog."default" NOT NULL,
    agency_timezone text COLLATE pg_catalog."default" NOT NULL,
    agency_lang text COLLATE pg_catalog."default" NOT NULL,
    agency_phone text COLLATE pg_catalog."default" NOT NULL,
    agency_fare_url text COLLATE pg_catalog."default" NOT NULL,
    agency_email text COLLATE pg_catalog."default" NOT NULL,
    agency_name_romanized text COLLATE pg_catalog."default" NOT NULL,
    agency_name_brand text COLLATE pg_catalog."default" NOT NULL,
    agency_state text COLLATE pg_catalog."default" NOT NULL,
    agency_logo_url text COLLATE pg_catalog."default" NOT NULL,
    agency_conditions_groups text COLLATE pg_catalog."default" NOT NULL,
    agency_conditions_children text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT agencies_pkey PRIMARY KEY (agency_id, agency_name, agency_url, agency_timezone, agency_lang, agency_phone, agency_fare_url, agency_email, agency_name_romanized, agency_name_brand, agency_state, agency_logo_url, agency_conditions_groups, agency_conditions_children)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.air_emissions
(
    airpol text COLLATE pg_catalog."default" NOT NULL,
    nace_r2 text COLLATE pg_catalog."default" NOT NULL,
    unit text COLLATE pg_catalog."default" NOT NULL,
    geo text COLLATE pg_catalog."default" NOT NULL,
    "TIME_PERIOD" text COLLATE pg_catalog."default" NOT NULL,
    obs_value double precision,
    CONSTRAINT air_emissions_pkey PRIMARY KEY (airpol, nace_r2, unit, geo, "TIME_PERIOD")
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.calendar
(
    service_id text COLLATE pg_catalog."default" NOT NULL,
    monday text COLLATE pg_catalog."default" NOT NULL,
    tuesday text COLLATE pg_catalog."default" NOT NULL,
    wednesday text COLLATE pg_catalog."default" NOT NULL,
    thursday text COLLATE pg_catalog."default" NOT NULL,
    friday text COLLATE pg_catalog."default" NOT NULL,
    saturday text COLLATE pg_catalog."default" NOT NULL,
    sunday text COLLATE pg_catalog."default" NOT NULL,
    start_date text COLLATE pg_catalog."default" NOT NULL,
    end_date text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT calendar_pkey PRIMARY KEY (service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.calendar_dates
(
    "UID" bigint,
    train_id text COLLATE pg_catalog."default",
    service_id text COLLATE pg_catalog."default",
    date timestamp with time zone,
    date_from text COLLATE pg_catalog."default",
    date_until text COLLATE pg_catalog."default",
    exception_type text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.classes
(
    class_id text COLLATE pg_catalog."default" NOT NULL,
    class_main text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT classes_pkey PRIMARY KEY (class_id, class_main)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.co2_emissions
(
    "Transporteur" text COLLATE pg_catalog."default",
    "Origine" text COLLATE pg_catalog."default",
    "Origine_uic" bigint,
    "Destination" text COLLATE pg_catalog."default",
    "Destination_uic" bigint,
    "Distance entre les gares" double precision,
    "Train - Empreinte carbone (kgCO2e)" double precision,
    "Distance aérienne" double precision,
    "Avion - Empreinte carbone (kgCO2e)" double precision
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.dim_date
(
    date_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    monday boolean NOT NULL,
    tuesday boolean NOT NULL,
    wednesday boolean NOT NULL,
    thursday boolean NOT NULL,
    friday boolean NOT NULL,
    saturday boolean NOT NULL,
    sunday boolean NOT NULL,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_id, start_date, end_date, monday, tuesday, wednesday, thursday, friday, saturday, sunday)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.dim_gare
(
    gare_id bigint,
    name text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    is_main_station boolean
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.dim_operateur
(
    agency_id text COLLATE pg_catalog."default",
    agency_name text COLLATE pg_catalog."default",
    agency_url text COLLATE pg_catalog."default",
    agency_country text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.dim_route
(
    route_id bigint NOT NULL,
    agency_id text COLLATE pg_catalog."default" NOT NULL,
    route_long_name text COLLATE pg_catalog."default" NOT NULL,
    origin text COLLATE pg_catalog."default" NOT NULL,
    destination text COLLATE pg_catalog."default" NOT NULL,
    countries text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_route_pkey PRIMARY KEY (route_id, agency_id, route_long_name, origin, destination, countries)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.dim_train
(
    trip_id text COLLATE pg_catalog."default",
    route_id bigint,
    trip_headsign text COLLATE pg_catalog."default",
    origin text COLLATE pg_catalog."default",
    destination text COLLATE pg_catalog."default",
    duration text COLLATE pg_catalog."default",
    distance text COLLATE pg_catalog."default",
    is_night_train boolean
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.fact_trajet_train
(
    fact_id bigint,
    train_id text COLLATE pg_catalog."default",
    route_id bigint,
    operator_id text COLLATE pg_catalog."default",
    gare_depart_id bigint,
    gare_arrivee_id bigint,
    date_id bigint,
    distance_km text COLLATE pg_catalog."default",
    duree_minutes text COLLATE pg_catalog."default",
    emissions_co2 double precision,
    passengers text COLLATE pg_catalog."default",
    average_speed text COLLATE pg_catalog."default",
    is_night_train boolean
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.gares_europeennes
(
    id bigint,
    name text COLLATE pg_catalog."default",
    slug text COLLATE pg_catalog."default",
    uic double precision,
    uic8_sncf double precision,
    latitude double precision,
    longitude double precision,
    parent_station_id double precision,
    country text COLLATE pg_catalog."default",
    is_city text COLLATE pg_catalog."default",
    is_main_station text COLLATE pg_catalog."default",
    is_airport text COLLATE pg_catalog."default",
    sncf_id text COLLATE pg_catalog."default",
    trenitalia_id double precision
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.horaires_des_gares
(
    "﻿﻿UIC" bigint NOT NULL,
    "Gare" text COLLATE pg_catalog."default" NOT NULL,
    "Jour de la semaine" text COLLATE pg_catalog."default" NOT NULL,
    "Horaire en jour normal" text COLLATE pg_catalog."default" NOT NULL,
    "Horaire en jour férié" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT horaires_des_gares_pkey PRIMARY KEY ("﻿﻿UIC", "Gare", "Jour de la semaine", "Horaire en jour normal", "Horaire en jour férié")
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.passenger_traffic_train_speed
(
    vehicle text COLLATE pg_catalog."default" NOT NULL,
    geo text COLLATE pg_catalog."default" NOT NULL,
    "TIME_PERIOD" text COLLATE pg_catalog."default" NOT NULL,
    obs_value double precision,
    CONSTRAINT passenger_traffic_train_speed_pkey PRIMARY KEY (vehicle, geo, "TIME_PERIOD")
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.passenger_transported
(
    unit text COLLATE pg_catalog."default" NOT NULL,
    geo text COLLATE pg_catalog."default" NOT NULL,
    "TIME_PERIOD" text COLLATE pg_catalog."default" NOT NULL,
    obs_value double precision,
    CONSTRAINT passenger_transported_pkey PRIMARY KEY (unit, geo, "TIME_PERIOD")
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.routes
(
    route_id bigint NOT NULL,
    agency_id text COLLATE pg_catalog."default" NOT NULL,
    agency_1 text COLLATE pg_catalog."default" NOT NULL,
    agency_2 text COLLATE pg_catalog."default" NOT NULL,
    agency_3 text COLLATE pg_catalog."default" NOT NULL,
    route_short_name text COLLATE pg_catalog."default" NOT NULL,
    route_long_name text COLLATE pg_catalog."default" NOT NULL,
    route_desc text COLLATE pg_catalog."default" NOT NULL,
    route_type bigint NOT NULL,
    version text COLLATE pg_catalog."default" NOT NULL,
    is_active text COLLATE pg_catalog."default" NOT NULL,
    origin_trip_0 text COLLATE pg_catalog."default" NOT NULL,
    destination_trip_0 text COLLATE pg_catalog."default" NOT NULL,
    distance text COLLATE pg_catalog."default" NOT NULL,
    emissions text COLLATE pg_catalog."default" NOT NULL,
    classes text COLLATE pg_catalog."default" NOT NULL,
    countries text COLLATE pg_catalog."default" NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    source_interrail text COLLATE pg_catalog."default" NOT NULL,
    picture text COLLATE pg_catalog."default" NOT NULL,
    emissions_relation text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT routes_pkey PRIMARY KEY (route_id, agency_id, agency_1, agency_2, agency_3, route_short_name, route_long_name, route_desc, route_type, version, is_active, origin_trip_0, destination_trip_0, distance, emissions, classes, countries, source, source_interrail, picture, emissions_relation)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.sncf_emissions
(
    transporteur text COLLATE pg_catalog."default",
    origine text COLLATE pg_catalog."default",
    origine_uic text COLLATE pg_catalog."default",
    destination text COLLATE pg_catalog."default",
    destination_uic text COLLATE pg_catalog."default",
    distance_entre_les_gares double precision,
    train_empreinte_carbone_kgco2e double precision,
    distance_routiere double precision,
    distance_aerienne double precision,
    avion_empreinte_carbone_kgco2e double precision,
    duree_estimee_min double precision
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.stops
(
    stop_id text COLLATE pg_catalog."default",
    stop_name text COLLATE pg_catalog."default",
    stop_country text COLLATE pg_catalog."default",
    stop_timezone text COLLATE pg_catalog."default",
    stop_lat double precision,
    stop_lon double precision,
    location_type text COLLATE pg_catalog."default",
    stop_name_romanized text COLLATE pg_catalog."default",
    stop_name_alt text COLLATE pg_catalog."default",
    stop_cityname text COLLATE pg_catalog."default",
    stop_cityname_romanized text COLLATE pg_catalog."default",
    stop_cityname_alt text COLLATE pg_catalog."default",
    stop_tariffname text COLLATE pg_catalog."default",
    stop_charge text COLLATE pg_catalog."default",
    stop_uic_code text COLLATE pg_catalog."default",
    stop_code text COLLATE pg_catalog."default",
    stop_region text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.train_traffic_source_energy
(
    train text COLLATE pg_catalog."default" NOT NULL,
    vehicle text COLLATE pg_catalog."default" NOT NULL,
    mot_nrg text COLLATE pg_catalog."default" NOT NULL,
    geo text COLLATE pg_catalog."default" NOT NULL,
    "TIME_PERIOD" text COLLATE pg_catalog."default" NOT NULL,
    obs_value double precision,
    CONSTRAINT train_traffic_source_energy_pkey PRIMARY KEY (train, vehicle, mot_nrg, geo, "TIME_PERIOD")
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.translations
(
    table_name text COLLATE pg_catalog."default" NOT NULL,
    field_name text COLLATE pg_catalog."default" NOT NULL,
    language_code text COLLATE pg_catalog."default" NOT NULL,
    translation text COLLATE pg_catalog."default" NOT NULL,
    record_id text COLLATE pg_catalog."default" NOT NULL,
    field_value text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT translations_pkey PRIMARY KEY (table_name, field_name, language_code, translation, record_id, field_value)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.trip_stops
(
    train_stop_id text COLLATE pg_catalog."default",
    trip_id text COLLATE pg_catalog."default",
    stop_sequence text COLLATE pg_catalog."default",
    stop_id text COLLATE pg_catalog."default",
    arrival_time text COLLATE pg_catalog."default",
    departure_time text COLLATE pg_catalog."default",
    no_exit text COLLATE pg_catalog."default",
    no_entry text COLLATE pg_catalog."default",
    border_control text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.trips
(
    route_id bigint,
    agency_id text COLLATE pg_catalog."default",
    trip_id text COLLATE pg_catalog."default",
    trip_origin text COLLATE pg_catalog."default",
    origin_departure_time text COLLATE pg_catalog."default",
    trip_headsign text COLLATE pg_catalog."default",
    destination_arrival_time text COLLATE pg_catalog."default",
    trip_short_name text COLLATE pg_catalog."default",
    direction_id bigint,
    version text COLLATE pg_catalog."default",
    countries text COLLATE pg_catalog."default",
    is_active text COLLATE pg_catalog."default",
    irregularities text COLLATE pg_catalog."default",
    service_id text COLLATE pg_catalog."default",
    classes text COLLATE pg_catalog."default",
    connections text COLLATE pg_catalog."default",
    catering text COLLATE pg_catalog."default",
    plugs text COLLATE pg_catalog."default",
    wheelchair_accessible text COLLATE pg_catalog."default",
    bikes_allowed text COLLATE pg_catalog."default",
    car_transport text COLLATE pg_catalog."default",
    duration time without time zone,
    distance text COLLATE pg_catalog."default",
    emissions_co2e text COLLATE pg_catalog."default",
    co2_per_km text COLLATE pg_catalog."default",
    via text COLLATE pg_catalog."default",
    "Merged Doc ID - ONTD_Chatbase_Export" text COLLATE pg_catalog."default",
    "Merged Doc URL - ONTD_Chatbase_Export" text COLLATE pg_catalog."default",
    "Link to merged Doc - ONTD_Chatbase_Export" text COLLATE pg_catalog."default",
    "Document Merge Status - ONTD_Chatbase_Export" text COLLATE pg_catalog."default",
    is_night_train boolean
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.view_ontd_cities
(
    stop_id text COLLATE pg_catalog."default" NOT NULL,
    stop_cityname_romanized text COLLATE pg_catalog."default" NOT NULL,
    stop_country text COLLATE pg_catalog."default" NOT NULL,
    stop_route_ids text COLLATE pg_catalog."default" NOT NULL,
    stop_cityname_route_ids text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT view_ontd_cities_pkey PRIMARY KEY (stop_id, stop_cityname_romanized, stop_country, stop_route_ids, stop_cityname_route_ids)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.view_ontd_details
(
    route_id bigint,
    agency_id text COLLATE pg_catalog."default",
    trip_short_name_0 text COLLATE pg_catalog."default",
    service_id_0 text COLLATE pg_catalog."default",
    trip_short_name_1 text COLLATE pg_catalog."default",
    service_id_1 text COLLATE pg_catalog."default",
    route_long_name text COLLATE pg_catalog."default",
    distance text COLLATE pg_catalog."default",
    average_speed text COLLATE pg_catalog."default",
    emissions text COLLATE pg_catalog."default",
    emissions_km text COLLATE pg_catalog."default",
    classes text COLLATE pg_catalog."default",
    countries text COLLATE pg_catalog."default",
    source text COLLATE pg_catalog."default",
    picture text COLLATE pg_catalog."default",
    irregularities_0 text COLLATE pg_catalog."default",
    irregularities_1 text COLLATE pg_catalog."default",
    connection text COLLATE pg_catalog."default",
    catering text COLLATE pg_catalog."default",
    plugs text COLLATE pg_catalog."default",
    wheelchair_accessible text COLLATE pg_catalog."default",
    bikes_allowed text COLLATE pg_catalog."default",
    car_transport text COLLATE pg_catalog."default",
    agency_id_1 text COLLATE pg_catalog."default",
    agency_name_1 text COLLATE pg_catalog."default",
    agency_url_1 text COLLATE pg_catalog."default",
    agency_logo_url_1 text COLLATE pg_catalog."default",
    agency_id_2 text COLLATE pg_catalog."default",
    agency_name_2 text COLLATE pg_catalog."default",
    agency_url_2 text COLLATE pg_catalog."default",
    agency_logo_url_2 text COLLATE pg_catalog."default",
    agency_id_3 text COLLATE pg_catalog."default",
    agency_name_3 text COLLATE pg_catalog."default",
    agency_url_3 text COLLATE pg_catalog."default",
    agency_logo_url_3 text COLLATE pg_catalog."default",
    monday_0 text COLLATE pg_catalog."default",
    tuesday_0 text COLLATE pg_catalog."default",
    wednesday_0 text COLLATE pg_catalog."default",
    thursday_0 text COLLATE pg_catalog."default",
    friday_0 text COLLATE pg_catalog."default",
    saturday_0 text COLLATE pg_catalog."default",
    sunday_0 text COLLATE pg_catalog."default",
    start_date_0 timestamp with time zone,
    end_date_0 timestamp with time zone,
    monday_1 text COLLATE pg_catalog."default",
    tuesday_1 text COLLATE pg_catalog."default",
    wednesday_1 text COLLATE pg_catalog."default",
    thursday_1 text COLLATE pg_catalog."default",
    friday_1 text COLLATE pg_catalog."default",
    saturday_1 text COLLATE pg_catalog."default",
    sunday_1 text COLLATE pg_catalog."default",
    start_date_1 timestamp with time zone,
    end_date_1 timestamp with time zone,
    trip_id_0 text COLLATE pg_catalog."default",
    trip_id_1 text COLLATE pg_catalog."default",
    duration_0 time without time zone,
    duration_1 time without time zone,
    origin_city text COLLATE pg_catalog."default",
    destination_city text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.view_ontd_list
(
    route_id text COLLATE pg_catalog."default" NOT NULL,
    night_train text COLLATE pg_catalog."default" NOT NULL,
    route_long_name text COLLATE pg_catalog."default" NOT NULL,
    itinerary text COLLATE pg_catalog."default" NOT NULL,
    itinerary_long text COLLATE pg_catalog."default" NOT NULL,
    countries text COLLATE pg_catalog."default" NOT NULL,
    operators text COLLATE pg_catalog."default" NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT view_ontd_list_pkey PRIMARY KEY (route_id, night_train, route_long_name, itinerary, itinerary_long, countries, operators, source)
);

CREATE TABLE IF NOT EXISTS tpre612_dataset_clean.view_ontd_map
(
    route_id bigint NOT NULL,
    agency_id text COLLATE pg_catalog."default" NOT NULL,
    trip_short_name_0 text COLLATE pg_catalog."default" NOT NULL,
    service_id_0 text COLLATE pg_catalog."default" NOT NULL,
    trip_short_name_1 text COLLATE pg_catalog."default" NOT NULL,
    service_id_1 text COLLATE pg_catalog."default" NOT NULL,
    route_long_name text COLLATE pg_catalog."default" NOT NULL,
    origin_trip_0 text COLLATE pg_catalog."default" NOT NULL,
    origin_departure_time_0 time without time zone NOT NULL,
    via_0 text COLLATE pg_catalog."default" NOT NULL,
    destination_trip_0 text COLLATE pg_catalog."default" NOT NULL,
    destination_arrival_time_0 time without time zone NOT NULL,
    origin_trip_1 text COLLATE pg_catalog."default" NOT NULL,
    origin_departure_time_1 time without time zone NOT NULL,
    via_1 text COLLATE pg_catalog."default" NOT NULL,
    destination_trip_1 text COLLATE pg_catalog."default" NOT NULL,
    destination_arrival_time_1 time without time zone NOT NULL,
    picture text COLLATE pg_catalog."default" NOT NULL,
    irregularities_0 text COLLATE pg_catalog."default" NOT NULL,
    irregularities_1 text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT view_ontd_map_pkey PRIMARY KEY (route_id, agency_id, trip_short_name_0, service_id_0, trip_short_name_1, service_id_1, route_long_name, origin_trip_0, origin_departure_time_0, via_0, destination_trip_0, destination_arrival_time_0, origin_trip_1, origin_departure_time_1, via_1, destination_trip_1, destination_arrival_time_1, picture, irregularities_0, irregularities_1)
);

ALTER TABLE IF EXISTS tpre612_data_warehouse.dim_route
    ADD CONSTRAINT dim_route_agency_id_fkey FOREIGN KEY (agency_id)
    REFERENCES tpre612_data_warehouse.dim_operateur (agency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tpre612_data_warehouse.dim_train
    ADD CONSTRAINT dim_train_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES tpre612_data_warehouse.dim_route (route_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tpre612_data_warehouse.fact_trajet_train
    ADD CONSTRAINT fact_trajet_train_gare_arrivee_id_fkey FOREIGN KEY (gare_arrivee_id)
    REFERENCES tpre612_data_warehouse.dim_gare (gare_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tpre612_data_warehouse.fact_trajet_train
    ADD CONSTRAINT fact_trajet_train_gare_depart_id_fkey FOREIGN KEY (gare_depart_id)
    REFERENCES tpre612_data_warehouse.dim_gare (gare_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tpre612_data_warehouse.fact_trajet_train
    ADD CONSTRAINT fact_trajet_train_operator_id_fkey FOREIGN KEY (operator_id)
    REFERENCES tpre612_data_warehouse.dim_operateur (agency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tpre612_data_warehouse.fact_trajet_train
    ADD CONSTRAINT fact_trajet_train_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES tpre612_data_warehouse.dim_route (route_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tpre612_data_warehouse.fact_trajet_train
    ADD CONSTRAINT fact_trajet_train_train_id_fkey FOREIGN KEY (train_id)
    REFERENCES tpre612_data_warehouse.dim_train (trip_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;